# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "Runner.xcworkspace", scheme: "Runner")
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: true)
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end

  desc "Release to App Store"
  lane :release do
    match(type: "appstore", readonly: true)
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store
  end

  desc "Build Debug (dev environment)"
  lane :build_dev do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", configuration: "Debug")
  end

  desc "Build Release (prod environment)"
  lane :build_prod do
    match(type: "appstore", readonly: true)
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", configuration: "Release")
  end
end
